### ISSUE TITLE
Text color change

### ISSUE THREAD

**Issue by jinjingfarm** [InterPSS-Project/ipss20#1]
Change text color from red to back. Red color usually means something is wrong.

![image](https://f.cloud.github.com/assets/5182378/942042/f6a98c84-016d-11e3-8866-704609469ccf.png)

**Comment by IpssDev** [comment]
Done with some other style enhancement: text is aligned center and border outline is removed.
![image](https://f.cloud.github.com/assets/5184193/943336/de42fa0a-020c-11e3-808a-fb9bfeca997e.png)

**Comment by jinjingfarm** [comment]
Issue resolved with V2.1.1 build-3
