### ISSUE TITLE
Save Existing Case GUI 

### ISSUE THREAD

**Issue by jinjingfarm** [InterPSS-Project/ipss20#12]
See the following figure:

![image](https://f.cloud.github.com/assets/5182378/977486/cc180d06-06a4-11e3-80c6-88991568410b.png)

**Comment by IpssDev** [comment]
If we add the check box, then there is no way for users to uncheck this option unless we provide it at another setting place. Do you think it is worth to do this?

**Comment by jinjingfarm** [comment]
We can add a new user property for this option. This is not a critical issue. We can implement in the future.
