### ISSUE TITLE
Help/InterPSS WebSite Link issue

### ISSUE THREAD

**Issue by jinjingfarm** [InterPSS-Project/ipss20#13]
Help/InerPSS WebSite ... link does not work:

![image](https://f.cloud.github.com/assets/5182378/990985/b52f34e8-094c-11e3-89c8-be919b05bc6c.png)

**Comment by IpssDev** [comment]
It worked as fine on my side. Could you provide more info about what happens when you click either one of the link?

**Comment by jinjingfarm** [comment]
Here is the URL on my side:

http://www.google.com/url?q=https%3A%2F%2Fsites.google.com%2Fa%2Finterpss.org%2Finterpss%2FHome%2Fuser-gude%2Finterpss-2-0-user-guide&sa=N&usd=2&usg=AFQjCNGo28va2buTY6TbWnkT2A2s7frDiw

**Comment by IpssDev** [comment]
Yes, you have to click to link to redirect to the destination. That's Google's design.

**Comment by jinjingfarm** [comment]
Even click the link does not work for me.

**Comment by jinjingfarm** [comment]
Error I got

![image](https://f.cloud.github.com/assets/5182378/993817/e79ac99c-09a1-11e3-90fc-39ccf641d336.png)

**Comment by IpssDev** [comment]
Hmmm, this is strange. When I click the link you provided in the previous comment, it shows as follows
![image](https://f.cloud.github.com/assets/5184193/995345/262a2b98-09bc-11e3-9111-234f2e0b30bc.png)

Then I click that link, it shows:
![image](https://f.cloud.github.com/assets/5184193/995350/3b6ea7ea-09bc-11e3-80b9-8315d9255ef2.png)

Could you try again? Maybe the network problem in your hotel?

I think this is a useful functionality for directing users to our website for more instructions.

**Comment by jinjingfarm** [comment]
I tried from different places using different connections. Please right-click one of the link, copy the URL and paste here. Then we can compare the difference.

**Comment by IpssDev** [comment]
This is my url:

The previous page is sending you to https://sites.google.com/a/interpss.org/interpss/Home/user-gude/interpss-2-0-user-guide.

 If you do not want to visit that page, you can return to the previous page.

**Comment by IpssDev** [comment]
This is the web address:

http://www.google.com/url?q=https%3A%2F%2Fsites.google.com%2Fa%2Finterpss.org%2Finterpss%2FHome%2Fuser-gude%2Finterpss-2-0-user-guide&sa=N&usd=2&usg=AFQjCNHdUChPTlsUvl-WuyIYZfsr098BVA

**Comment by jinjingfarm** [comment]
This is a Browser security issue. My browser is set to "Google Chrome is using your computer's system proxy settings to connect to the network.". If I hit the link inside a Linux VM, it works.

There is not easy to reset the browser proxy setting.

**Comment by jinjingfarm** [comment]
The menuitem has been in hiding status.
