### ISSUE TITLE
Auto loading sheet issue

### ISSUE THREAD

**Issue by jinjingfarm** [InterPSS-Project/ipss20#14]
All sheets are cleared except the Log, Bsues, Branch Input:

![image](https://f.cloud.github.com/assets/5182378/991014/746842b4-094d-11e3-978d-5ef5d35b8868.png)

Save the spreadsheet and re-load, the following sheets are added automatically:

![image](https://f.cloud.github.com/assets/5182378/991016/96854cca-094d-11e3-8d41-2eb0f15b6b3c.png)

**Comment by IpssDev** [comment]
This is as expected. It is for the purpose of avoiding sometimes having to refresh the sheet to display the content of a sheet. When the sheets are created before hand, based on my testing, it can reduce the possibility of this situation.

**Comment by jinjingfarm** [comment]
Since most people are not going to run DCLF, so let us keep the Branches State sheet, and remove the LODF Result sheet and Cont Ana Result sheet.

**Comment by IpssDev** [comment]
If we just leave sheet: Log, Buses, Branches Input, I encountered the previous issue, which is that after complete a Ac lf calculation, we have to manually refresh the app to display the sheet "Branches state". However, it is your call.

**Comment by jinjingfarm** [comment]
Let us add  "Branches state" to the initial sheet list.

![image](https://f.cloud.github.com/assets/5182378/1016271/d9c50944-0bf5-11e3-9ee9-de38e0939245.png)
