### ISSUE TITLE
Disable PQ+ option

### ISSUE THREAD

**Issue by jinjingfarm** [InterPSS-Project/ipss20#2]
Currently, PQ+ method is not implemented in the InterPSS core simulation engine. Therefore, the option needs to be disabled.

![image](https://f.cloud.github.com/assets/5182378/942044/98bb3e32-016e-11e3-9067-07736910a686.png)

**Comment by IpssDev** [comment]
Done.
![image](https://f.cloud.github.com/assets/5184193/943340/5cf8b416-020d-11e3-8658-ad165a20e7e3.png)

**Comment by jinjingfarm** [comment]
Issue resolved with V2.1.1 build-3
