### ISSUE TITLE
Post-contingency flow issue

### ISSUE THREAD

**Issue by jinjingfarm** [InterPSS-Project/ipss20#22]
When there are multiple contingencies, 

![image](https://f.cloud.github.com/assets/5182378/1022963/bfb0f33a-0dbf-11e3-8b7a-477564298a77.png)

The post-contingency flow is the same as pre-flow:

![image](https://f.cloud.github.com/assets/5182378/1022964/e4c14350-0dbf-11e3-9283-2f24f95a1902.png)

**Comment by IpssDev** [comment]
During the execution, there was actually an exception:
com.interpss.pssl.util.ContingencyAnalysisHelper contAnalysis: Contingency: Contingency 1  com.interpss.core.dclf.common.ReferenceBusException: Inject bus is the ref bus, bus sensitivity cache id: PAngle_Bus1  RefBusId: Bus1, Swing

Bus1 is the swing bus and branch 1-5(1) is a outage branch. I don't know why this exception did not be catched correctly and some results are returned.

**Comment by IpssDev** [comment]
Just figured it out. The exception was catched and handled in the ContingencyAnalysisHelper class. For the fix, shall the code assign another reference bus or return warnings to users?

**Comment by jinjingfarm** [comment]
Just like LODF calculation, we can add the ref bus option:

![image](https://f.cloud.github.com/assets/5182378/1029567/d86b009c-0e9a-11e3-81ec-97a1edaf5e48.png)

Also, we need to warn user if ref bus is connected to an outage branch.

**Comment by jinjingfarm** [comment]
Pending on Issue #23

**Comment by jinjingfarm** [comment]
Issue resolved with V2.2.1 build-2
