### ISSUE TITLE
too detailed log info regarding the case raw data and result

### ISSUE THREAD

**Issue by thuang** [InterPSS-Project/ipss20#24]
![ipss2 0 log is caching too much info](https://f.cloud.github.com/assets/529196/1036832/21ab9a1a-0f44-11e3-817f-56a32eeceaa9.jpg)

I don't think it is necessary to cache such detailed info in the log section. This may affect the performance. Some progress and/or operation info should be enough.

**Comment by IpssDev** [comment]
I am doing some debug on issue #23. I just print this info out for debug purpose. It will not display during production.
