### ISSUE TITLE
DCLF Report Output "Undefined"

### ISSUE THREAD

**Issue by thuang** [InterPSS-Project/ipss20#25]
DCLF report is not supported at this moment, right?  After running DCLF, it produced an empty report .txt file, which the GDrive determines as "Undefined".

A related issue is the report setting in the User setting. Now the label is named as "load flow report", which may make users confused and get a wrong idea that only load flow result can be output to the GDrive.

**Comment by IpssDev** [comment]
I have this issue has been fixed in v2.2.1. Please confirm.

**Comment by jinjingfarm** [comment]
Issue resolved with V2.2.1 Final Release
