### ISSUE TITLE
Error during loading input data

### ISSUE THREAD

**Issue by jinjingfarm** [InterPSS-Project/ipss20#27]
The following error was seen during loading an input file. However, it issue cannot be duplicated.

![image](https://f.cloud.github.com/assets/5182378/1041890/148ed820-0fde-11e3-8c22-e13990a2e4b4.png)

![image](https://f.cloud.github.com/assets/5182378/1042360/1dabac9c-0fea-11e3-92f8-74d0a629d6bd.png)

![image](https://f.cloud.github.com/assets/5182378/1042363/25555132-0fea-11e3-9705-03fdef9b53f5.png)

**Comment by jinjingfarm** [comment]
We will watch to see if the issue occurs again in the future.

**Comment by jinjingfarm** [comment]
When a wrong input date format is selected, for example, selected IEEE Common Format for an input file of ODM format, we will get the above error. We need a better error message to inform the user.

**Comment by IpssDev** [comment]
This issue was caused by issue: https://github.com/InterPSS-Project/ipss-odm/issues/2
