### ISSUE TITLE
Spreadsheet permission 

### ISSUE THREAD

**Issue by jinjingfarm** [InterPSS-Project/ipss20#28]
When login as user and trying to open the App Template, I got the following msg:

![image](https://f.cloud.github.com/assets/5182378/1042772/7e3d22d6-0ff2-11e3-83f8-12ceb230faaa.png)

**Comment by IpssDev** [comment]
Sorry I don't get it. What is the issue?

**Comment by jinjingfarm** [comment]
App Template permission not set correctly.
