### ISSUE TITLE
Result output GDrive file naming convention

### ISSUE THREAD

**Issue by jinjingfarm** [InterPSS-Project/ipss20#3]
The following format is recommended:

![image](https://f.cloud.github.com/assets/5182378/942050/917e784a-016f-11e3-9e23-36a28737a8c4.png)

where %...% are substitution variables.

%Module% -> Aclf or Dclf
%filename% -> use actual file name
%datetime% -> use datetime, for example 05-05-2013-12:23:05

**Comment by IpssDev** [comment]
Done.
![image](https://f.cloud.github.com/assets/5184193/943510/9ffce772-0222-11e3-849e-156868abde1a.png)

The time is formatted based on user's time zone, which is set in the script's user properties:
![image](https://f.cloud.github.com/assets/5184193/943511/cc78d82e-0222-11e3-8d8d-f43cdb84a6c3.png)

**Comment by jinjingfarm** [comment]
We need to make sure the module, filename and datetime are dynamic.

**Comment by jinjingfarm** [comment]
The timing of substitution is not correct.

For the file name template:

%Module% Report %filename% %datetime%.txt

In the current implementation does the substitution when user edits the User Settings and assumes that before each run user will edit the Settings. This is not always the case. 

The substitution should happens when the result file gets created. In other words, when saving the result file, use the template to dynamically create the filename, instead of reading the filename from the User Settings. In this way, the info is always correct.

**Comment by IpssDev** [comment]
Then what is the point of letting user to edit this template? Shall we just put a label instead of text box there? Users can edit the title in their GDrive anyway.

**Comment by jinjingfarm** [comment]
User might do

My %Module% Report %filename% --- %datetime%.txt

or 

%Module% Report %datetime% %filename%.txt

So the %...% is, what is called, substitution variable, which will be replaced at run time.

**Comment by IpssDev** [comment]
I personally think that this will cause come unnecessary complications since users can change the tittle in their GDrive. I will suggest to keep it simple for maintenance purpose. Please try the new look and feedback.

**Comment by jinjingfarm** [comment]
The new interface look great. Currently, the filename format is fixed. In the future, if there is a need, we can open it to the user for modification. V2.1.1 Build-5
