### ISSUE TITLE
Wrong CA result when Find Constrained Branch option checked 

### ISSUE THREAD

**Issue by jinjingfarm** [InterPSS-Project/ipss20#6]
When the Find Constrained Branch option is checked, the CA result is wrong, see the following sample screen:

![image](https://f.cloud.github.com/assets/5182378/942060/2727e92a-0171-11e3-92d5-8fef78fd1673.png)

**Comment by IpssDev** [comment]
New CA input settins:

![image](https://f.cloud.github.com/assets/5184193/973674/899f9dfc-0638-11e3-80b0-49b12ac674ab.png)

Result outlook:

![image](https://f.cloud.github.com/assets/5184193/973682/fd62f6bc-0638-11e3-9a59-3f486aa2bef1.png)

**Comment by jinjingfarm** [comment]
This issue is pending on resolving Issue #9

**Comment by jinjingfarm** [comment]
A wrong screen shot was attached to the issue. The following is the correct screen shot for the original issue:

![image](https://f.cloud.github.com/assets/5182378/977311/eefefacc-06a0-11e3-9a50-2f21ccc0f8d5.png)

**Comment by IpssDev** [comment]
This happens when you check the findConstrainedBranch and do not specify the MvaRatingB in the Branches Input sheet. Put the mouse above the check box and see the hints.

**Comment by jinjingfarm** [comment]
After defining MvaRatingB, I can get:

![image](https://f.cloud.github.com/assets/5182378/977589/d5f76914-06a6-11e3-989d-ac59d95d3520.png)

Recommendation:  If MvaRatingB is not defined, or are all zero, out put a warning message on the log page.

**Comment by jinjingfarm** [comment]
Issue resolved V2.1.1 Build-5
