### ISSUE TITLE
LODF Settings enhancement

### ISSUE THREAD

**Issue by jinjingfarm** [InterPSS-Project/ipss20#7]
Add the Ref Bus Id option. The default value is set to the system swing bus. It is possible that the system swing bus is an outage branch terminal bus. For multi-line LODF testing, please see ipss.test.QA/~/DclfLODFPaper_Test.java.

![image](https://f.cloud.github.com/assets/5182378/942880/0e4cda7a-01dd-11e3-8831-6f7ec7a9d5c7.png)

**Comment by IpssDev** [comment]
Done. With LODF settings as follows,
![image](https://f.cloud.github.com/assets/5184193/973663/4225efc6-0638-11e3-9419-3a9bfb27c144.png)

The results are as follows,
![image](https://f.cloud.github.com/assets/5184193/973664/4fbf065e-0638-11e3-98c8-85864206f68d.png)

Which matches the test case: ipss.test.QA/~/DclfLODFPaper_Test.java.

**Comment by jinjingfarm** [comment]
V2.1.1 Build-3, see image below:

![image](https://f.cloud.github.com/assets/5182378/975766/6dc9818c-067f-11e3-8cff-358e0f6f1472.png)

**Comment by jinjingfarm** [comment]
Issue resolved with V2.1.1 Build-4
