### ISSUE TITLE
Multiple CA option

### ISSUE THREAD

**Issue by jinjingfarm** [InterPSS-Project/ipss20#8]
Currently, when a 2nd contingency is added, the previous entered contingency is overwritten:

![image](https://f.cloud.github.com/assets/5182378/942901/e4a193b2-01de-11e3-8c2a-5e201af48b03.png)

In order to do multiple CA, we need to allow multiple CA defined, as follows:

![image](https://f.cloud.github.com/assets/5182378/942902/f97beb3e-01de-11e3-82d6-237a7017b7ce.png)

**Comment by IpssDev** [comment]
The definition of multiple CA is not clear to me. Did you mean:
1. Store multiple CA information in the sheet and provide another GUI to let users to select one of them to run? 
2. Run a bunch of analysis for all contingencies listed in the sheet? 
3. Others?

**Comment by jinjingfarm** [comment]
Run all CAs and output the result in sequence. The common usage is to find constrained branches for all CAs.

![image](https://f.cloud.github.com/assets/5182378/962992/b9511b60-04f9-11e3-839f-6600a91ff527.png)

**Comment by jinjingfarm** [comment]
Issue open for V2.1.1 Build-3

**Comment by jinjingfarm** [comment]
Issue resolved with V2.1.1 Build-4
